version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: titan-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: titan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root7769
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: titan-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
