version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: titan-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: titan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root7769
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: titan-redis
    ports:
      - "6379:6379"

  orchestrator:
    build: ./titan-orchestrator
    container_name: titan-orchestrator
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/titan_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root7769
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  orchestrator-replica:
    build: ./titan-orchestrator
    container_name: titan-orchestrator-replica
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/titan_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root7769
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  worker:
    build: ./titan-worker
    container_name: titan-worker
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/titan_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root7769
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
